### ISSUE TITLE
Regarding overclocking

### ISSUE THREAD

**Issue by Yrahate7** [Andy1911/AndyKernel_ZukZ1#1]
Hey Andy
If you please look at the commit linked below, we might have the answer to overclock our device
https://github.com/andip71/boeffla-kernel-cm-bacon/commit/bf2b438a12e6751b0603c6795e4defc903c70ef7

**Comment by Andy1911** [comment]
Commits have been added. Thanks for help. But already tried these Commits

Regards
Andy
